typography_spectrum: 0.2768262915778905
color:
  brandColors:
    - '#000000'
    - '#404040'
    - '#808080'
    - '#BFBFBF'
    - '#FFFFFF'
  brandStrength: 0.35734103131107986
  lightness: 0.7418812406249344
  saturation: 0.9614877987187356
  rhythmicContrast: 0.8113932970445603
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.43168
analytics:
  google: null
  facebook: null
  twitter: null
name: turning japanese
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Portfolio
    url: 'http://www.fstopchef.com'
    type: external
  - name: Tokyo
    id: 1d7ac27f-d786-4c45-a48a-ff7a02ff0bd7
    type: content
favicon: null
title: Turning Japanese
description: absorbing culture
purpose: []
