name: turning japanese
favicon: null
layout_spectrum: 0.10899
typography_spectrum: 0.02296
title: turning Japanese
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0a050a'
    - '#434a53'
    - '#a98068'
    - '#2d221d'
    - '#ff3d5c'
  brandStrength: 0.8610976652707905
  lightness: 0.5625
  saturation: 0.625
  rhythmicContrast: 0.5
purpose: []
