typography_spectrum: 0.02296
color:
  brandColors:
    - '#0a050a'
    - '#434a53'
    - '#a98068'
    - '#2d221d'
    - '#ff3d5c'
  brandStrength: 0.8610976652707905
  lightness: 0.5625
  saturation: 0.625
  rhythmicContrast: 0.75
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.84863
analytics:
  google: null
  facebook: null
  twitter: null
name: turning japanese
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: photo portfolio
    url: 'http//:www.fstopchef.com'
    type: external
favicon: null
title: turning Japanese
description: absorbing culture
purpose: []
